### ISSUE TITLE
Ca marche pas pour windows

### ISSUE THREAD

**Issue by Diegovano** [matu1003/LecteurNSI#1]
Du moins je pense!!!

**Comment by matu1003** [comment]
C'est possible... T'as bien fait pip install playsound?

**Comment by matu1003** [comment]
Ok j'ai trouvé, l'alphabet phonetique (IPA) n'est pas inclu dans le module "epitran" ce qui causait une erreur

**Comment by Diegovano** [comment]
Voici l'erreur que j'ai: Je ne sais pas si tu peux resoudre de ton cote. (J'ai aussi essayé de convertir les .m4a en .mp3)
```sh
Diego@Diego-PC MINGW64 /d/Downloads/LecteurNSI-master/LecteurNSI-master
$ python Main.py
Traceback (most recent call last):
  File "Main.py", line 46, in <module>
    pron_sounds(["a"])
  File "Main.py", line 44, in pron_sounds
    playsound("SonsMat/"+son)
  File "C:\Users\Diego\AppData\Local\Programs\Python\Python38\lib\site-packages\playsound.py", line 35, in _playsoundWin
    winCommand('open "' + sound + '" alias', alias)
  File "C:\Users\Diego\AppData\Local\Programs\Python\Python38\lib\site-packages\playsound.py", line 31, in winCommand
    raise PlaysoundException(exceptionMessage)
playsound.PlaysoundException:
    Error 277 for command:
        open "SonsMat/a.m4a" alias playsound_0.938948472480695
    A problem occurred in initializing MCI.
```

**Comment by matu1003** [comment]
Est ce que les premiers sons fonctionnent puisque le "a" n'est pas le premier son joué...

**Comment by Diegovano** [comment]
Je pense que aucun son ne fonctionne
